/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppRouterLink: typeof import('./components/AppRouterLink.vue')['default']
    AppSettings: typeof import('./components/AppSettings.vue')['default']
    IconIonEarthOutline: typeof import('~icons/ion/earth-outline')['default']
    IconIonInformationCircleOutline: typeof import('~icons/ion/information-circle-outline')['default']
    IconIonLanguage: typeof import('~icons/ion/language')['default']
    IconIonLogoGithub: typeof import('~icons/ion/logo-github')['default']
    IconIonSettingsOutline: typeof import('~icons/ion/settings-outline')['default']
    LanguageSelector: typeof import('./components/LanguageSelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToolBar: typeof import('./components/ToolBar.vue')['default']
    VersionInfo: typeof import('./components/VersionInfo.vue')['default']
  }
}
