/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppRouterLink: typeof import('./components/AppRouterLink.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconCustomCommunity: typeof import('~icons/custom/community')['default']
    IconCustomDocumentation: typeof import('~icons/custom/documentation')['default']
    IconCustomEcosystem: typeof import('~icons/custom/ecosystem')['default']
    IconCustomSupport: typeof import('~icons/custom/support')['default']
    IconCustomTooling: typeof import('~icons/custom/tooling')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./components/TheWelcome.vue')['default']
    VersionInfo: typeof import('./components/VersionInfo.vue')['default']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
  }
}
